import Link from 'next/link'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import { BlockRenderer } from './blocks'
import Appendix from './Appendix'
import ArticleShare from './ArticleShare'
import InlineSubscribe from './InlineSubscribe'
import type { RenderableIssue } from './payload-adapter'

export default function ArticleRenderer({
  issue,
  issueId,
}: {
  issue: RenderableIssue
  // Optional — when present, ArticleRenderer renders the deterministic
  // hero banner (and the explained-simply banner) generated by the
  // /issue/[id]/hero-image* route handlers. Older preview surfaces that
  // don't have a real issue id continue to render the text-only header.
  issueId?: string
}) {
  return (
    <>
      {/* HERO — Lenny/Stratechery-style v6: deterministic banner image
          generated server-side via next/og precedes the text header. The
          image is a 1600x500 PNG with Issue NNN + dateline + title + byline
          baked in, so the very first paint of the page reads like an
          editorial cover, not a wall of text. */}
      {issueId ? (
        <div className="border-b border-line bg-bg">
          <div className="mx-auto max-w-read px-5 pt-8 sm:px-8 sm:pt-10">
            {/* Plain <img> on purpose — next/image would re-encode the PNG
                through its optimizer and lose the deterministic-cache
                advantage of the next/og route handler. */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={`/issue/${issueId}/hero-image`}
              alt={`AI Signal — ${issue.title}`}
              width={1600}
              height={500}
              className="block h-auto w-full"
            />
          </div>
        </div>
      ) : null}
      <header className="border-b border-line">
        <div className="mx-auto max-w-read px-5 pb-14 pt-14 sm:px-8 sm:pt-20">
          <Link
            href="/"
            className="mb-12 inline-flex min-h-[44px] items-center gap-2 text-[13px] font-medium text-fg-muted transition-colors hover:text-fg"
          >
            <ArrowLeft size={14} strokeWidth={2} />
            All issues
          </Link>
          <div className="mb-7 flex flex-wrap items-center gap-x-3 gap-y-1 text-[13px] text-fg-muted">
            <span className="font-medium uppercase tracking-[0.1em] text-fg-subtle">
              Issue {issue.no}
            </span>
            {issue.kind === 'DEEP DIVE' ? (
              <>
                <span aria-hidden className="text-fg-subtle">
                  ·
                </span>
                <span className="font-semibold text-lime-soft">Deep dive</span>
              </>
            ) : null}
            <span aria-hidden className="text-fg-subtle">
              ·
            </span>
            <span>{issue.heroDate}</span>
          </div>
          <h1 className="font-serif text-[40px] font-semibold leading-[1.02] tracking-[-0.015em] text-fg sm:text-[64px]">
            {issue.title}
          </h1>
          {issue.dek ? (
            <p className="mt-6 max-w-[680px] font-serif text-[21px] font-normal leading-[1.4] text-fg-muted sm:text-[24px]">
              {issue.dek}
            </p>
          ) : null}
          <div className="mt-10 flex items-center gap-4 border-t border-line pt-6">
            <span
              className="flex h-11 w-11 items-center justify-center rounded-full bg-lime-bright font-serif text-[18px] font-bold text-fg"
              aria-hidden
            >
              S
            </span>
            <div className="flex flex-1 flex-col gap-0.5">
              <p className="text-[15px] font-semibold text-fg">
                Suraj Pandita
              </p>
              <p className="text-[13px] text-fg-muted">
                Bangalore · {issue.read.toLowerCase()} read
              </p>
            </div>
            <ArticleShare title={issue.title} />
          </div>
          {issue.lede ? (
            <div className="editorial editorial-lede mt-10" dangerouslySetInnerHTML={{ __html: issue.lede }} />
          ) : null}
        </div>
      </header>

      {/* SIGNAL OF THE WEEK — Editorial v2 — the ONE screenshot-worthy line.
          Renders only when payload includes the field (new synthesizer
          output). Large serif pullquote with lime mark. */}
      {issue.signal_of_the_week ? (
        <section className="border-b border-line">
          <div className="mx-auto max-w-read px-5 py-14 sm:px-8 sm:py-20">
            <p className="text-[13px] font-semibold uppercase tracking-[0.08em] text-fg-muted">
              The signal
            </p>
            <p className="mt-6 font-serif text-[26px] font-medium leading-[1.3] tracking-[-0.005em] text-fg sm:text-[36px]">
              {issue.signal_of_the_week}
            </p>
          </div>
        </section>
      ) : null}

      <main className="mx-auto max-w-read px-5 sm:px-8">
        {issue.chapters.map((ch, idx) => {
          const last = idx === issue.chapters.length - 1
          // Editorial moat anchor: the Glance chapter is the only chapter
          // where the human directly picked (Ship/Hold/Kill). Single lime tick
          // marks it as the editorial moment of the issue.
          const isMoat = ch.id === 'ch-glance'
          return (
            <section
              key={ch.id}
              id={ch.id}
              className={`scroll-mt-32 pb-16 pt-20 ${last ? '' : 'border-b border-line'}`}
            >
              <h2 className="font-serif text-[32px] font-medium leading-[1.1] tracking-tight text-fg sm:text-[40px]">
                {isMoat ? (
                  <span
                    className="mr-3 inline-block -translate-y-1 text-lime"
                    aria-hidden
                  >
                    →
                  </span>
                ) : null}
                {ch.heading}
              </h2>
              {ch.sub && (
                <p className="mt-3 max-w-[520px] font-serif text-[18px] italic leading-snug text-cream-dim">{ch.sub}</p>
              )}
              <div className="mt-9 flex flex-col gap-9">
                {ch.blocks.map((b, i) => (
                  <BlockRenderer key={i} block={b} />
                ))}
              </div>
            </section>
          )
        })}
      </main>

      {/* EXPLAINED SIMPLY — Editorial v2 — one concept in Feynman register.
          Renders only when payload includes it. */}
      {issue.explained_simply ? (
        <section className="border-t border-line">
          {issueId ? (
            <div className="mx-auto max-w-read px-5 pt-12 sm:px-8 sm:pt-14">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={`/issue/${issueId}/hero-image-explained`}
                alt={`Explained simply — ${issue.explained_simply.concept}`}
                width={1600}
                height={400}
                className="block h-auto w-full"
              />
            </div>
          ) : null}
          <div className="mx-auto max-w-read px-5 py-16 sm:px-8 sm:py-20">
            <p className="text-[13px] font-semibold uppercase tracking-[0.08em] text-fg-muted">
              Explained simply
            </p>
            <h2 className="mt-4 font-serif text-[32px] font-semibold leading-[1.08] tracking-[-0.015em] text-fg sm:text-[44px]">
              {issue.explained_simply.concept}.
            </h2>
            <p className="mt-8 max-w-[640px] text-[18px] leading-[1.65] text-fg-muted sm:text-[19px]">
              {issue.explained_simply.explanation}
            </p>
          </div>
        </section>
      ) : null}

      {/* PRODUCTION QUESTIONS — Editorial v2 — real Monday-morning questions.
          Renders only when payload includes ≥1 question. */}
      {issue.production_questions && issue.production_questions.length ? (
        <section className="border-t border-line">
          <div className="mx-auto max-w-read px-5 py-16 sm:px-8 sm:py-20">
            <p className="text-[13px] font-semibold uppercase tracking-[0.08em] text-fg-muted">
              From the standup
            </p>
            <h2 className="mt-4 font-serif text-[32px] font-semibold leading-[1.08] tracking-[-0.015em] text-fg sm:text-[44px]">
              Three real questions in the air this week.
            </h2>
            <ol className="mt-10 flex flex-col gap-7">
              {issue.production_questions.map((q, i) => (
                <li key={i} className="flex gap-6 border-t border-line pt-7">
                  <span className="shrink-0 font-serif text-[20px] font-semibold text-lime-soft">
                    {i + 1}
                  </span>
                  <p className="max-w-[640px] text-[18px] leading-[1.55] text-fg">
                    {q}
                  </p>
                </li>
              ))}
            </ol>
          </div>
        </section>
      ) : null}

      {/* INLINE SUBSCRIBE — Lenny standard: mid-article CTA between body and
          appendix. Light card, joined input+button. Reuses /api/subscribe. */}
      <InlineSubscribe />

      {/* APPENDIX — interview drills + further reading (web only, lean email).
          Conditional on payload.appendix; older issues without it render
          nothing here. Drills are topic-aware (per fresh-model audit
          2026-06-16); resources include the India-builder differentiator. */}
      {issue.appendix && <Appendix appendix={issue.appendix} issueId={issueId} />}

      {/* CLOSURE — Lenny-style personal sign-off. No "—— That's the shift"
          performative terminal; just a thank-you, a forward-to-one-builder
          ask, and an italic Suraj signature next to the same avatar from
          the byline. Keeps the personal-newsletter register the rest of the
          article promises. */}
      <section className="border-t border-line">
        <div className="mx-auto max-w-read px-5 py-20 sm:px-8 sm:py-24">
          <p className="max-w-[560px] font-serif text-[22px] leading-[1.45] text-fg sm:text-[24px]">
            Thanks for reading. If this lands, forward it to one builder who
            shouldn&apos;t miss this week&apos;s shift.
          </p>
          <p className="mt-6 max-w-[520px] text-[16px] leading-[1.65] text-fg-muted">
            I&apos;ll be back Monday at 7:30 AM IST with the next one. Reply
            with what you&apos;re shipping — I read every email.
          </p>

          <div className="mt-10 flex items-center gap-4">
            <span
              className="flex h-11 w-11 items-center justify-center rounded-full bg-lime-bright font-serif text-[18px] font-bold text-fg"
              aria-hidden
            >
              S
            </span>
            <div className="flex flex-col gap-0.5">
              <p className="font-serif text-[19px] italic leading-tight text-fg">
                — Suraj
              </p>
              <p className="text-[13px] text-fg-muted">
                Bangalore · suraj@getaisignal.org
              </p>
            </div>
          </div>

          <div className="mt-12 flex flex-wrap items-center gap-x-6 gap-y-3 border-t border-line pt-7 text-[14px]">
            <Link
              href="/#subscribe"
              className="group inline-flex min-h-[44px] items-center font-medium text-fg transition-colors hover:text-lime-soft"
            >
              Subscribe free
              <ArrowRight
                size={14}
                strokeWidth={2.25}
                className="ml-1.5 transition-transform group-hover:translate-x-0.5"
              />
            </Link>
            <span aria-hidden className="text-fg-subtle">
              ·
            </span>
            <Link
              href="/#archive"
              className="inline-flex min-h-[44px] items-center text-fg-muted transition-colors hover:text-fg"
            >
              Read past issues
            </Link>
          </div>
        </div>
      </section>
    </>
  )
}
